'''This file contains GHG data imported from the excel file submited''' 
'''Please ensure the data provided in the excel file is correct'''

project_phases = {'CONSTRUCTION': {'phase': 'CONSTRUCTION', 'years': 2.5}, 'OPERATION': {'phase': 'OPERATION', 'years': 50.0}}

energy = {'Grid Electricity for Site Equipment': {'phase': 'CONSTRUCTION', 'type': 'CONSUMED', 'source': 'Grid Electricity for Site Equipment', 'quantity': 0.5, 'ef': 0.55}, 'Pumping Operations': {'phase': 'OPERATION', 'type': 'CONSUMED', 'source': 'Pumping Operations', 'quantity': 22, 'ef': 0.55}, 'Construction Site Lighting': {'phase': 'CONSTRUCTION', 'type': 'CONSUMED', 'source': 'Construction Site Lighting', 'quantity': 0.3, 'ef': 0.55}, 'Hydropower Energy Generation': {'phase': 'OPERATION', 'type': 'PRODUCED', 'source': 'Hydropower Energy Generation', 'quantity': 2325.354166666667, 'ef': 0.004}}

vehicles = {'Construction Trucks': {'phase': 'CONSTRUCTION', 'type': 'ROAD', 'vehicle': 'Construction Trucks', 'distance': 15000, 'n_vehicles': 4, 'co2_emissions': 0.0015, 'ch4_emissions': 1e-05, 'ch4_cf': 25, 'n2o_emissions': 2e-05, 'n2o_cf': 298}, 'Personnel Transport': {'phase': 'CONSTRUCTION', 'type': 'ROAD', 'vehicle': 'Personnel Transport', 'distance': 8000, 'n_vehicles': 2, 'co2_emissions': 0.0015, 'ch4_emissions': 1e-05, 'ch4_cf': 25, 'n2o_emissions': 2e-05, 'n2o_cf': 298}, 'Material Transport': {'phase': 'CONSTRUCTION', 'type': 'ROAD', 'vehicle': 'Material Transport', 'distance': 12000, 'n_vehicles': 3, 'co2_emissions': 0.0015, 'ch4_emissions': 1e-05, 'ch4_cf': 25, 'n2o_emissions': 2e-05, 'n2o_cf': 298}, 'Soil Excavation Trucks': {'phase': 'CONSTRUCTION', 'type': 'ROAD', 'vehicle': 'Soil Excavation Trucks', 'distance': 10000, 'n_vehicles': 2, 'co2_emissions': 0.0015, 'ch4_emissions': 1e-05, 'ch4_cf': 25, 'n2o_emissions': 2e-05, 'n2o_cf': 298}, 'Reservoir Liner Trucks': {'phase': 'CONSTRUCTION', 'type': 'ROAD', 'vehicle': 'Reservoir Liner Trucks', 'distance': 7000, 'n_vehicles': 1, 'co2_emissions': 0.0015, 'ch4_emissions': 1e-05, 'ch4_cf': 25, 'n2o_emissions': 2e-05, 'n2o_cf': 298}, 'General Utility Vehicles': {'phase': 'CONSTRUCTION', 'type': 'ROAD', 'vehicle': 'General Utility Vehicles', 'distance': 9000, 'n_vehicles': 2, 'co2_emissions': 0.0015, 'ch4_emissions': 1e-05, 'ch4_cf': 25, 'n2o_emissions': 2e-05, 'n2o_cf': 298}}

fixed_combustion = {'Site Generators': {'phase': 'CONSTRUCTION', 'enginery_fueltype': 'Site Generators', 'quantity': 10000, 'n_machines': 1, 'ef': 0.00268}, 'Water Pumps Backup': {'phase': 'OPERATION', 'enginery_fueltype': 'Water Pumps Backup', 'quantity': 5000, 'n_machines': 1, 'ef': 0.00268}, 'Workshop Generator': {'phase': 'CONSTRUCTION', 'enginery_fueltype': 'Workshop Generator', 'quantity': 3000, 'n_machines': 1, 'ef': 0.00268}, 'Desalination Backup': {'phase': 'OPERATION', 'enginery_fueltype': 'Desalination Backup', 'quantity': 4000, 'n_machines': 1, 'ef': 0.00268}}

mobile_combustion = {'Excavators': {'phase': 'CONSTRUCTION', 'enginery_fueltype': 'Excavators', 'quantity': 12000, 'n_machines': 2, 'co2_emissions': 0.00268, 'ch4_emissions': 1e-06, 'ch4_cf': 25, 'n2o_emissions': 1e-06, 'n2o_cf': 298}, 'Cranes': {'phase': 'CONSTRUCTION', 'enginery_fueltype': 'Cranes', 'quantity': 8000, 'n_machines': 1, 'co2_emissions': 0.00268, 'ch4_emissions': 1e-06, 'ch4_cf': 25, 'n2o_emissions': 1e-06, 'n2o_cf': 298}, 'Concrete Mixers': {'phase': 'CONSTRUCTION', 'enginery_fueltype': 'Concrete Mixers', 'quantity': 7000, 'n_machines': 2, 'co2_emissions': 0.00268, 'ch4_emissions': 1e-06, 'ch4_cf': 25, 'n2o_emissions': 1e-06, 'n2o_cf': 298}, 'Bulldozers': {'phase': 'CONSTRUCTION', 'enginery_fueltype': 'Bulldozers', 'quantity': 11000, 'n_machines': 2, 'co2_emissions': 0.00268, 'ch4_emissions': 1e-06, 'ch4_cf': 25, 'n2o_emissions': 1e-06, 'n2o_cf': 298}, 'Tippers': {'phase': 'CONSTRUCTION', 'enginery_fueltype': 'Tippers', 'quantity': 9000, 'n_machines': 2, 'co2_emissions': 0.00268, 'ch4_emissions': 1e-06, 'ch4_cf': 25, 'n2o_emissions': 1e-06, 'n2o_cf': 298}, 'Water Trucks': {'phase': 'CONSTRUCTION', 'enginery_fueltype': 'Water Trucks', 'quantity': 6000, 'n_machines': 1, 'co2_emissions': 0.00268, 'ch4_emissions': 1e-06, 'ch4_cf': 25, 'n2o_emissions': 1e-06, 'n2o_cf': 298}}

materials_prod = {'Excavated Earth': {'phase': 'CONSTRUCTION', 'material': 'Excavated Earth', 'process': 'reservoir and tunnel excavation', 'quantity': 2000000, 'ef': 1e-05}, 'Cut Basalt': {'phase': 'CONSTRUCTION', 'material': 'Cut Basalt', 'process': 'reservoir shaping yields basalt fragments used/reused on site', 'quantity': 500000, 'ef': 1.5e-05}, 'Construction Debris': {'phase': 'CONSTRUCTION', 'material': 'Construction Debris', 'process': 'non-hazardous waste from temporary structures', 'quantity': 300000, 'ef': 2e-05}, 'Concrete Waste': {'phase': 'CONSTRUCTION', 'material': 'Concrete Waste', 'process': 'estimated at 3–5% of total concrete volume used', 'quantity': 150000, 'ef': 3e-05}, 'Steel Scrap': {'phase': 'CONSTRUCTION', 'material': 'Steel Scrap', 'process': 'off-cuts and rebar trimmings during fabrication phase', 'quantity': 50000, 'ef': 2.5e-05}, 'Liner Scraps': {'phase': 'CONSTRUCTION', 'material': 'Liner Scraps', 'process': 'HDPE offcuts during geomembrane laying process', 'quantity': 20000, 'ef': 3e-05}}

materials_use = {'Concrete': {'phase': 'CONSTRUCTION', 'material': 'Concrete', 'quantity': 5000000, 'ef': 0.00013}, 'Steel': {'phase': 'CONSTRUCTION', 'material': 'Steel', 'quantity': 800000, 'ef': 0.0019}, 'HDPE Geomembrane': {'phase': 'CONSTRUCTION', 'material': 'HDPE Geomembrane', 'quantity': 120000, 'ef': 0.003}, 'Asphalt': {'phase': 'CONSTRUCTION', 'material': 'Asphalt', 'quantity': 300000, 'ef': 6e-05}, 'Gravel': {'phase': 'CONSTRUCTION', 'material': 'Gravel', 'quantity': 1000000, 'ef': 5e-06}, 'Reinforced Bar': {'phase': 'CONSTRUCTION', 'material': 'Reinforced Bar', 'quantity': 400000, 'ef': 0.0018}}

soil_use = {}

waste_treatm = {}

