import app

print (app.plot_total_peryear())
print (app.plot_energy_peryear())
print (app.plot_fixedcomb_peryear())
print (app.plot_mobilecomb_peryear())
print (app.plot_materialsprod_peryear())
print (app.plot_vehicles_all_peryear())
print (app.plot_vehicles_road_peryear())
print (app.plot_vehicles_train_peryear())
print (app.plot_vehicles_ship_peryear())
print (app.plot_vehicles_air_peryear())
print (app.plot_waste_all_peryear())
print (app.plot_waste_solids_peryear())
print (app.plot_waste_water_peryear())
print (app.plot_waste_gas_peryear())

print (app.show_total)
print (app.show_energy)
print (app.show_vehicles)
print (app.show_combustionmachinery)
print (app.show_materials)
print (app.show_soilusechange)
print (app.show_wastetreatment)